### ISSUE TITLE
Zero to iex

### ISSUE THREAD

**Issue by bugthing** [dhanson358/nerves_system_nanopi_neo#4]
I have a nanopi neo and I would love to try Nerves on it, problem is I dont really know where to start.
Looks like you've done lots of work to get it running but I am not sure how to use this repo.
Could you provide some basic commands to get this running on the device so I can (for example) get an `iex` prompt (or something) running on the device.

I just wanna play with elixir on this tiny thing but not sure where or how to start.
many thanks,
-b

**Comment by dhanson358** [comment]
The easiest way to get started, if you don't need to customize buildroot at all, would probably be to just include a link to one of the releases in this project in your project mix.exs.  For example, you might include something like this to get the latest release.

    [{:"nerves_system_nanopi_neo",
      git: "https://github.com/dhanson358/nerves_system_nanopi_neo.git",
      ref: "v0.0.50"}]

If you need to customize the buildroot for some reason, that's significantly more complicated.  However, I suspect most of the patching I have in this repo (in order to support the neo) is now part of the mainline linux kernel.  When I was working on this a year ago a lot of this was starting to be pulled into mainline, so I'm sure it's more complete now.

**Comment by bugthing** [comment]
I tried add this to mix.exs and ran into version conflicts. I think I'll familiarise myself with nerves better on a supported device before continuing trying to get it running on this nanopi. 
Many thanks. -b
